name: acme-tutorials
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.25
  - scipy>=1.8
  - matplotlib>=3.5,<3.9
  - pandas>=1.4
  - xarray
  - astropy
  - h5py>=3.6
  - jupyterlab
  - ipykernel
  - ipywidgets>=8.0
  - notebook<7.0
  - make
  - gcc
  - pip
  - pip:
      - corner
      - eryn
      - gbgpu
      - ellc
      - tqdm
      - tables
      - sympy
      - gpubackendtools
      - git+https://github.com/mikekatz04/LISAanalysistools.git
      - git+https://gitlab.in2p3.fr/Nikos/gwg.git
      - whittaker-eilers
      - fastgb
      - scikit-learn
      - torch
      - torchvision
      - torchmetrics
      - mlxtend
      - torchinfo
      - seaborn
      - joblib
